### ISSUE TITLE
Getting an error during Netlify deploy (and npm run build)

### ISSUE THREAD

**Issue by BobWalsh** [jpmonette/feed#118]
**Describe the bug**
```
4:57:41 PM: TypeError: Cannot read property '_collection' of undefined
4:57:41 PM:     at api.afterBuild (/opt/build/repo/node_modules/@microflash/gridsome-plugin-feed/index.js:74:55)
4:57:41 PM:     at Plugins.run (/opt/build/repo/node_modules/gridsome/lib/app/Plugins.js:141:17)
```

**To Reproduce**
1. install plugin
2. gridsome develop works
3. npm run build on Netlify fails:

**Expected behavior**
A clean build

**Actual behavior**
```
4:57:41 PM: TypeError: Cannot read property '_collection' of undefined
4:57:41 PM:     at api.afterBuild (/opt/build/repo/node_modules/@microflash/gridsome-plugin-feed/index.js:74:55)
4:57:41 PM:     at Plugins.run (/opt/build/repo/node_modules/gridsome/lib/app/Plugins.js:141:17)
```

**Screenshots**
<img width="1556" alt="Cursor_and_Deploy_details___remote-or-else" src="https://user-images.githubusercontent.com/5097/78086006-7cc4ea80-7371-11ea-986d-f56714e8dcfb.png">

**Versions (please complete the following information):**
 - NodeJS: node v10.19.0
 - TypeScript: n/a
 - npm/yarn: npm v6.13.4

**Comment by jpmonette** [comment]
@BobWalsh Not sure what is the relationship with jpmonette/feed module - maybe raise issue at `@microflash/gridsome-plugin-feed`?

Closing.
