### ISSUE TITLE
Stream support

### ISSUE THREAD

**Issue by Mister-Hope** [jpmonette/feed#119]
I have about 500 markdown files which have a total size up to 10M to generate, for now, it's taking a bit more memory while rendering. Can we use stream, to write contents directly to the files while reading them? Just like what `sitemap` is doing.

**Comment by gtamas** [comment]
@jpmonette 
Any news about this? Will you add stream support anytime soon?
I'm facing the same issue. Buffering is not good when there is an ever growing number of feed items.

**Comment by jpmonette** [comment]
@gtamas Good idea! I welcome PRs - just raise a Feature Request with how you'd implement it and you can then push a PR.

Thanks
