### ISSUE TITLE
Export types in feed

### ISSUE THREAD

**Issue by gustavkj** [jpmonette/feed#128]
**Is your feature request related to a problem? Please describe.**
Right now, only [the `Feed` class is exported](https://github.com/jpmonette/feed/blob/41842ab1b7b73a941c84a75f522092c1627a8529/src/feed.ts#L9) as a type. It would be nice if the types used for the parameters of different methods and the constructor were exported to.

**Describe the solution you'd like**
Export the following types: `Author`, `Extension`, `FeedOptions`, and `Item`.

**Describe alternatives you've considered**
In the meantime, I'm getting the type from the typing of the parameters. Which I do not think is as nice, though:

```ts
import { Feed } from 'feed';

type Item = Parameters<Feed['addItem']>[0];
```

It's also possible to get the type by importing from the `typings` directory, but it do not think this is an intended feature (right?):

```ts
import { Item } from 'feed/lib/typings';
```

**Additional context**

For reference, `feed.d.ts` looks like this as of `4.2.1`:

```ts
import { Author, Extension, FeedOptions, Item } from "./typings";
export declare class Feed {
    options: FeedOptions;
    items: Item[];
    categories: string[];
    contributors: Author[];
    extensions: Extension[];
    constructor(options: FeedOptions);
    addItem: (item: Item) => number;
    addCategory: (category: string) => number;
    addContributor: (contributor: Author) => number;
    addExtension: (extension: Extension) => number;
    atom1: () => string;
    rss2: () => string;
    json1: () => string;
}
```

**Comment by jpmonette** [comment]
@gustavkj Good catch. You can open a PR!

**Comment by gustavkj** [comment]
@jpmonette Thanks! Sure, I've opened a [PR](https://github.com/jpmonette/feed/pull/136) now.
