### ISSUE TITLE
Docs??? Tutorial?

### ISSUE THREAD

**Issue by anoduck** [jpmonette/feed#165]
**Is your feature request related to a problem? Please describe.**

I am not a javascript programmer, not yet anyway, and from the example provided, it appears fairly easy to configure this to generate a rss feed for a site that does not provide one. The problem is, since I am not more than a novice programming javascript, I have no idea how to implement it. The sample script in the README.md is all that is provided. It would be nice if there were more examples and perhaps instruction on exactly how to use this app.

**Describe the solution you'd like**

Documentation and examples on exactly how to use this library.

**Describe alternatives you've considered**

Giving up on it, with the chance of returning to it several years from now, after I no longer need the solution.

**Additional context**
"Add any other context or screenshots about the feature request here. Also make sure to add any documentation related."

- Documentation, that would be nice.

**Comment by CanRau** [comment]
Know it's kinda late maybe, but wanted to check in if you solved it or if I might be able to help.

If you haven't solved it I'd need some more info on how you're generating your website?
Do you use [Remix](https://remix.run/), NodeJS (with or without Express), Gatsby, NextJS, or something else?

**Comment by jpmonette** [comment]
@anoduck I think the current readme is pretty self-explanatory with basic JavaScript/TypeScript knowledge. I'm open to suggestions if there's some tweaks that can be made to the docs, but the current readme includes a complete copy/pasteable snippet that should work out of the box.

**Comment by anoduck** [comment]
@jpmonette I am not questioning what you are saying by any degree. Admittedly, it is apparent this "basic Javascript/Typescript knowledge" is not existent, and I am out of my league attempting to employ this library for a site I have been working on.

@CanRau Thank you so much for the offer, it is very generous. 

In building a website for a non-profit, the ability to generate a webpage that would mirror posts made to a public group page on social media. The website is built on top of Hugo, I was hoping to use this library to generate an RSS feed of those posts, and then have Hugo render the RSS feed on a page. Then set it all to recreate the feed periodically to update that feed.

Does this make any sense? I am rather sleep-deprived.

**Comment by CanRau** [comment]
@anoduck I've no personal experience with Hugo but sounds like you should be better of finding Hugo native ways to generate RSS feeds or not?

**Comment by anoduck** [comment]
@CanRau The project has been put on pause for the moment, which give me some time to perform research on the best way to do this. Hugo does have a built-in RSS feed generator, but it is designed to generate RSS feeds for itself, and not for a remote site. Regardless, I am sure something will be figured out when the time comes. 

Cheers, and thanks again for your kindness.

**Comment by CanRau** [comment]
Uuh hmm ok I see, hope you'll find a good solution in time 🙌

**Comment by yataghan012** [comment]
@anoduck Have you managed to make a RSS feed of a remote site with this tool?

Would you make a friendly explanation of how to do this to a non-programmer?

**Comment by anoduck** [comment]
@yataghan012 Unfortunately, I never did, and there is no longer a need to do so. In retrospect, I was both out of my league, and probably using the tool in a manner it was not intended to be used for. I mostly program in python, and only have just begun to scratch the surface of working with javascript. 

Not sure what your particular needs are, but there are numerous services that offer feed generation from website content available. The page I was attempting to scrape was a social media platform, specifically the organization's profile page. Which is why a custom solution was needed.

**Comment by yataghan012** [comment]
@anoduck I just need something that lets me do RSS out of news sites that don't have it and some bitchute channels. Basically.

**Comment by anoduck** [comment]
Checkout this repo, it has an up to date list of tools for RSS, and includes information that is well past my knowledge base. They even have a telegram channel, from what I can tell. 
[All About RSS](https://github.com/AboutRSS/ALL-about-RSS)

Not a big fan of Ruby, but this seems to run off a CLI, and is what I ran across earlier in my browsing. Might be the best solution of the bunch.
[html2rss](https://github.com/html2rss/html2rss)

If you are into using scrapy, this would help. If not, then it is never too late to start. I usually use selenium to scrape content, and am just beginning to acquire familiarity with scrapy. 
[scrapy_RSS](https://github.com/woxcab/scrapy_rss)

Lastly, if you dabble in php, there is this. Again, just beginning to gain familiarity with php.
[rss-scraper](https://github.com/baraveli/rss-scraper)

Hope it helps.
