### ISSUE TITLE
validateURL is not nice function

### ISSUE THREAD

**Issue by YaroslavGaponov** [jpmonette/feed#23]
I mean it possible problems for local hostname like http://myworknotebook etc

**Comment by alexlangberg** [comment]
Yup. To add to this, it would at least be handy for the error to indicate *which* of the potentially hundreds of links is invalid. It would be nice to change it to this:

    if(!validateURL(entries[i].link))
      throw new Error('invalid entry link');

... to this:

    if(!validateURL(entries[i].link))
      throw new Error('invalid entry link: ' + entries[i].link);

**Comment by alexlangberg** [comment]
It also seems to fail, even on valid urls such as:

    https://foo.com/bar/?baz=bax

A suggestion could be to use the validator module:

https://www.npmjs.com/package/validator

Or pick up their version of url validation:

https://github.com/chriso/validator.js/blob/master/validator.js#L200-L260

**Comment by goodseller** [comment]
+1

**Comment by ArtskydJ** [comment]
Fixed in 761272c1f58fb10dc3bee0060c88de1e1e242fea?

**Comment by jpmonette** [comment]
Removed validation on URL - developer is free to write them valid.
