### ISSUE TITLE
Lots of commits missing in npm

### ISSUE THREAD

**Issue by EyePulp** [jpmonette/feed#35]
Howdy - thanks for your work on this package.  Would it be possible to bump your version and publish to npm?  I see a number of good fixes that aren't available on the npm version from 2 years ago.

Thanks!

**Comment by jpmonette** [comment]
@EyePulp Thanks for the kick in the butt - all there :+1: 
https://www.npmjs.com/package/feed

**Comment by EyePulp** [comment]
Fantastic - thank you kindly!

**Comment by jpmonette** [comment]
I planned to update the repo a couple of months ago with tests and such. Will also review the pull request in the pipeline.
