### ISSUE TITLE
New line is not transformed to <BR>

### ISSUE THREAD

**Issue by giacecco** [jpmonette/feed#42]
If I add `\n` to the text in the "description" field of a feed entry, it is not transformed in `<br>` or something equivalent in the RSS feed. Is that a bug? Thanks.

**Comment by danger89** [comment]
Please reopen. This is a bug! \n should be converted to HTML/XML break line. Especially since the content is between the `<![CDATA[` stuff.
```js
const betterDescription = String(desc).replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g, '$1<br />$2');
```
