### ISSUE TITLE
Items in feed not added image property

### ISSUE THREAD

**Issue by fabionolasco** [jpmonette/feed#63]
Hi jpmonette! I added the image property on the object that are passed to feed.addItem(obj), but the resulting feed does not show the image property on item level.

Source code generating my feed (line 88):
[https://github.com/fabionolasco/fire-feed/blob/master/server.js](https://github.com/fabionolasco/fire-feed/blob/master/server.js)

Generated feed:
[http://fabionolasco.com:3322/rss](http://fabionolasco.com:3322/rss)

**Comment by fabionolasco** [comment]
Just a note: I saw in your personal feed a field called media:content. Should this Node plugin add the same field?

http://blogue.jpmonette.net/rss/

**Comment by zfoster** [comment]
I am experiencing this as well

**Comment by serman** [comment]
I think It is a simple bug: 
file feed.js:374 it says:
`if (item.image) {
          item.push({ enclosure: [{ _attr: { url: entry.image } }] });
        }`
and it must say: 
`if (entry.image) {
          item.push({ enclosure: [{ _attr: { url: entry.image } }] });
        }`
