### ISSUE TITLE
Feed support for Category on Items

### ISSUE THREAD

**Issue by gruberjl** [jpmonette/feed#71]
Hey,

I didn't see any documentation on this package to support categories on the feed items.

Categories on feed items is supported by RSS.
http://cyber.harvard.edu/rss/rss.html#hrelementsOfLtitemgt

I couldn't find any code in this package to support the category for items in RSS (I may have missed it).

Is category on feed items supported in this package?
Is their a reason it was intentionally left out?

**Comment by jpmonette** [comment]
@gruberjl It's not implemented and no reason for being left out. Feel free to create a PR.

**Comment by gruberjl** [comment]
No problem thanks. Upon reviewing a handful of other RSS feeds, categories aren't heavily implemented. If I end up needing them I'll create a PR.
