### ISSUE TITLE
Example Code, `posts` Undefined

### ISSUE THREAD

**Issue by monico-moreno** [jpmonette/feed#78]
**Describe the bug**
Unless the [example code](https://github.com/jpmonette/feed#example) is not meant to be copy/pasted to work out of the box, the variable `posts` needs needs to be defined.  

**To Reproduce**
1. Go to [example code](https://github.com/jpmonette/feed#example)
2. copy and paste code into local env
3. run code
4. See error, _"ReferenceError: posts is not defined"_

**Expected behavior**
Code should run.

**Actual behavior**
Error from above.

**Screenshots**
none

**Versions (please complete the following information):**
 - NodeJS: v10.10
 - TypeScript: none
 - npm/yarn: v6.4.1
 - feed: n/a

**Additional context**
n/a

**Comment by monico-moreno** [comment]
I suppose I could create a PR for this, but I wanted to get it down quickly.   Please do let me know if you prefer a PR for this.

**Comment by jpmonette** [comment]
Closing as no response.

**Comment by strefethen** [comment]
@jpmonette 

I just started looking at this repo this afternoon (very nice btw), and I tripped on this too.

+1 for "Code is not meant to be copy/pasted. "posts" should be a list of items pulled from a data store from which to build your feed's items.


> @monico-moreno Code is not meant to be copy/pasted straight, but maybe it should (or at least have a mention that it's not meant to be straight up copy/pasted). Developer must get his `posts` from database - you can look at the unit test as a demo.
> 
> What would you suggest as a PR?
