### ISSUE TITLE
item.id is ignored in rss output

### ISSUE THREAD

**Issue by ArtskydJ** [jpmonette/feed#96]
**Describe the bug**
src/rss2.ts looks at `entry.guid`, not `entry.id` as documented (implied) in the readme.
https://github.com/jpmonette/feed/blob/master/src/rss2.ts#L117-L121

**Expected behavior**
- `entry.guid` should be documented OR
- the code should look at `entry.id` instead

**Actual behavior**
`entry.guid` is not documented, but is being used.

**Versions (please complete the following information):**
 - feed: I think since version 1.

**Additional context**
Workaround: submit both the `entry.guid` and the `entry.id`

Also, the test didn't catch this issue. If this test line was changed then the tests would catch the issue.
https://github.com/jpmonette/feed/blob/master/src/__tests__/setup.ts#L34

```diff
  sampleFeed.addItem({
    title: "Hello World",
-   id: "https://example.com/hello-world",
+   id: "0123456789abcdef-0123-4567-89abcdef"
    link: "https://example.com/hello-world",
    description: "This is an article about Hello World.",
```

**Comment by jpmonette** [comment]
@ArtskydJ A PR is welcomed to support this 💪🏼.

**Comment by ArtskydJ** [comment]
Would you rather have me change the docs to `guid`, or the code to `id`?

**Comment by KnicKnic** [comment]
So I just wasted a bunch of time on this! My personal preference is to remove guid, and bring the rss2 into alignment with atom & json. However this will break backwards compat.

I think the below code would be the best compromise.
```javascript
    if (entry.guid) {
      item.guid = { _text: entry.guid };
    } else if (entry.id) {
      item.guid = { _text: entry.id };
    } else if (entry.link) {
      item.guid = { _text: entry.link };
    }
```

**Comment by danger89** [comment]
yea pretty strange bug... Please solve :\
