### ISSUE TITLE
Add extra attributes on <rss> tag

### ISSUE THREAD

**Issue by elchiconube** [jpmonette/feed#98]
I need to add some extra/custom attributes on my xml

For example on `<rss>` I expect to create something like this:
```
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/"   xmlns:amzn="https://amazon.com/ospublishing/1.0/">
``` 

Also on `<channel>` tag I want to add another tag for example 
```
<amzn:rssVersion>1.0</amzn:rssVersion>
```

Thanks for your time and work, you awesome!

**Comment by jpmonette** [comment]
Please fill in the Feature Request template.

**Comment by itinance** [comment]
Is there any possible approach to add these attributes on the <rss>-node?
